### ISSUE TITLE
Get new favico.ico that is not trademark protected

### ISSUE THREAD

**Issue by jcass77** [pimusicbox/pimusicbox.github.io#2]
I think the use of the Raspberry Pi logo may be in contravention of the foundation's trademark rules: https://www.raspberrypi.org/trademark-rules/

I also saw at least one unanswered query on the Facebook page from what appears to be one of the official representatives: https://www.facebook.com/raspberrypimusicbox/posts_to_page

**Comment by woutervanwijk** [comment]
Yes that's true. I answered it by mail and removed the logo. Should indeed be removed from everything. 

Verstuurd vanaf mijn iPhone

**Comment by jodal** [comment]
I've removed the favicon from the web site and docs site now. Should we leave this open until we get a replacement?
