### ISSUE TITLE
waarkan ik de iso downloaden??

### ISSUE THREAD

**Issue by mattie2324** [pimusicbox/pimusicbox.github.io#4]
hallo waarkan ik de iso downlaoden??
als ik naar jullie site ga en ik druk op de downloadlink krijg ik een error page van github

**Comment by kingosticks** [comment]
English please

**Comment by jcass77** [comment]
Wants to know where he can download the ISO from.

Apparently the link no longer works?

**Comment by jcass77** [comment]
@mattie2324, I've checked the link on the [musicbox website](http://www.pimusicbox.com) and [https://dl.mopidy.com/pimusicbox/pimusicbox-0.6.0.zip](https://dl.mopidy.com/pimusicbox/pimusicbox-0.6.0.zip) seems to work? Closing this now - please reopen with details of the links that you are using if you still experience any problems?

I don't really speak Dutch but it is close enough to Afrikaans that this might help you: Die skakel in die boodskap hierbo kom van die Pi Musicbox webblad af en kan gebruik word om die ISO af te laai. Ek het dit so vining getoets en dit lyk asof dit werk. Open asseblief weer hierdie fout verslag indien jy verdere probleme ondervind?

**Comment by onnlinetool** [comment]
Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden 

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi
